language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install --upgrade pip
  - pip install coverage tox-travis virtualenv coveralls
script:
  - tox
  - coverage run --rcfile=.coveragerc setup.py test -s tests.unit
  - bash tests/local_installation_test.sh
after_success:
  coveralls
notifications:
  email:
    on_failure: change
dist: xenial
sudo: false
